# See here for image contents: https://github.com/users/mwinters-stuff/packages/container/package/vscode-devcontainer-raspberrypi-pico

FROM ghcr.io/mwinters-stuff/vscode-devcontainer-raspberrypi-pico:latest

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends 
